export const environment = {
  production: true,
  baseAuthUrl: 'http://10.0.0.17:8081/api/',
  baseUrl: 'http://10.0.0.17:8080/api/',
  TOKEN_KEY: 'access_token',
  LOGIN: 'login',
  USERNAME: 'username',
  ADMIN: 'Admin',
  MATERIE_PRIME: 'materie-prime',
  MATERIE_PRIME_REGISTRO: 'materie-prime-registro',
  PRODOTTI:'prodotti',
  PRODOTTO_MATERIE_PRIME:'prodotto-materie-prime',
  LISTINI:'listini',
  TIPO_PRODOTTI:'tipo-prodotti',
  MATERIE_PRIME_WEBER: 'materie-prime-weber',
  MATERIE_PRIME_REGISTRO_WEBER: 'materie-prime-registro-weber',
  PRODOTTI_WEBER:'prodotti-weber',
  PRODOTTO_MATERIE_PRIME_WEBER:'prodotto-materie-prime-weber',
  TIPO_PRODOTTI_WEBER:'tipo-prodotti-weber'
};
